[project]
name = "rag-for-rag-papers"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11, <3.13"
dependencies = [
    "pypdf",
    "langchain-text-splitters",
    "langchain",
    "langchain-huggingface",
    "langchain-community",
    "langchain-chroma",
    "sentence-transformers>=5.2.0",
]
